version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2184:2181"
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zookeeper
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 140.143.238.102
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  redis:
    image: redis
    ports:
      - "6378:6379"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root